---
- name: Learn Magic Variables
  hosts: nodes
  gather_facts: false
  tasks:
    - name: Show Inventory Host Name
      debug:
        msg: "{{ inventory_hostname }}"
    - name: Show Group
      debug:
        msg: "{{ group_names }}"

    - name: Show Host Variable
      debug:
        msg: "{{ hostvars }}"
