- name: Package Installation
  hosts: nodes
  become: yes
  tasks:
    - block:
        - name: Show Message
          debug: 
            msg: "Trying httpd"

        - name: Install Package
          yum:
            name: httpd-wrong
            state: present
      rescue:
        - name: Show error
          debug:
            msg: "Unknown Package"
        - name: Install nginx
          yum:
            name: nginx
            state: latest

      always:
        - name: Message
          debug:
            msg: "Playbook Done"
