- name: Package Installation
  hosts: nodes
  become: yes
  tasks:
    - name: Say hello
      ansible.builtin.debug:
        msg: "Hello"

    - name: Install some packages
      ansible.builtin.yum:
        name: nginx
        state: present
        
    - block:
        - name: Show Message
          ansible.builtin.debug: 
            msg: "Trying httpd"

        - name: Install Package
          ansible.builtin.yum:
            name: httpd-wrong
            state: present
      rescue:
        - name: Show error
          ansible.builtin.debug:
            msg: "Unknown Package"
        - name: Install nginx
          ansible.builtin.yum:
            name: nginx
            state: latest

      always:
        - name: Message
          ansible.builtin.debug:
            msg: "Playbook Done"
