---
- name: Run a Command
  hosts: nodes
  become: true
  tasks:
    - name: Check Uptime
      shell: 'uptime'
      register: shell_output

    - name: Print the output
      ansible.builtin.debug:
        msg: "{{ shell_output.stdout_lines }}"
