---
- name: Ansible Fact Demo
  hosts: nodes
  gather_facts: false
  tasks:
    - name: collect facts
      ansible.builtin.setup:
    - name: Show details
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} {{ ansible_hostname }} {{ ansible_default_ipv4['address'] }}"
